#!/bin/bash

#echo "java -jar /home/felipe/Downloads/acotsp-example/GA.jar $5 $6 $7 $8 $9"

java -jar /home/luanb/Luan/Unicamp/11_Semestre/MO824/trabalho/workspace/Atividade6/iraceGA/bin/GA.jar $4 $5 $6 $7 $8 $9

exit $?
